# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9850b3fc53a4671eb3038771b26ddf0f833465f75f5ca1825443a191cda0b0731846a94fbe17f7aac6c3e56eea750a4d13834e8e6ec1f74ebec9e79545315645

test:
  secret_key_base: 90e06a653ec7ad37b0f41874511ef22bf72b66333f1cd10c44f9dc0c28f468e5a87da3a2530324b7efbda30bc37b2b3303fe292ac099453a96b62ee9a90a03e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
